### ISSUE TITLE
CustomCentroidBondForce represented under NonbondedForce in energycomponent

### ISSUE THREAD

**Issue by sandrabyju** [smog-server/OpenSMOG#94]
The added CustomCentroidBondForce (system.addForce) gets represented under NonbondedForce in energycomponent output file.

**Comment by Whitford** [comment]
Ok, this is happening because opensmog has a force dictionary that is used by the reporters.  Since you are adding a force to the model without adding it to the dictionary, the last force (i.e. the centroid force) gets listed under the index of the first force (nonbonded).  I'll write a wrapper that allows for any force to be added in a way that is consistent with the rest of opensmog.

**Comment by Whitford** [comment]
I added a new routine called addForce.  This ensures that the name is also added to the dictionary, which is needed to properly report the energy.  See commit a5d26a3 for details.
